import { Transaction } from "@/types/mockData";

export interface ExtendedTransaction extends Transaction {
  account: string;
  notes: string;
  behaviorComparison: string;
  aiExplanation: string;
}

export const mockExtendedTransactions: ExtendedTransaction[] = [
  {
    id: "tx-1001",
    amount: 45000.00,
    currency: "INR",
    merchant: "HDFC Bank Loan EMI",
    category: "debt_repayment",
    date: "2026-07-08T10:00:00Z",
    type: "debit",
    status: "completed",
    riskScore: 12,
    account: "HDFC Current (A/C 1145)",
    notes: "Monthly vehicle loan EMI deduction.",
    behaviorComparison: "Consistent with previous 12 billing cycles.",
    aiExplanation: "Typical scheduled ledger payment. Zero anomaly marks detected in payment velocity."
  },
  {
    id: "tx-1002",
    amount: 152000.00,
    currency: "INR",
    merchant: "TCS Client Invoice Inflow",
    category: "income",
    date: "2026-07-07T14:30:00Z",
    type: "credit",
    status: "completed",
    riskScore: 2,
    account: "Yes Bank Savings (A/C 9812)",
    notes: "Milestone payment for logistics consulting module deliverables.",
    behaviorComparison: "Matches scheduled client invoicing timeline.",
    aiExplanation: "Inflow from verified business counterparty. Adds 1.5 months to liquidity runway buffer."
  },
  {
    id: "tx-1003",
    amount: 3500.00,
    currency: "INR",
    merchant: "Swiggy Delivery",
    category: "leisure",
    date: "2026-07-06T20:15:00Z",
    type: "debit",
    status: "completed",
    riskScore: 8,
    account: "Corporate Credit Card (CCN-2983)",
    notes: "Team lunch order for engineering sprint kickoff session.",
    behaviorComparison: "Within typical discretionary spending bounds for this team.",
    aiExplanation: "Recognized merchant and standard ordering hour velocity."
  },
  {
    id: "tx-1004",
    amount: 18500.00,
    currency: "INR",
    merchant: "AWS Cloud Infrastructure",
    category: "utilities",
    date: "2026-07-05T01:10:00Z",
    type: "debit",
    status: "completed",
    riskScore: 15,
    account: "Corporate Credit Card (CCN-2983)",
    notes: "AWS monthly hosting bill for staging and testing clusters.",
    behaviorComparison: "12% higher than last month's AWS outflow due to testing cycles.",
    aiExplanation: "Minor usage increase in server instances. Aligning pre-purchase commitment packages is recommended."
  },
  {
    id: "tx-1005",
    amount: 110000.00,
    currency: "INR",
    merchant: "Nexa Global Wire Transfer",
    category: "business",
    date: "2026-07-04T12:00:00Z",
    type: "debit",
    status: "pending",
    riskScore: 92,
    account: "HDFC Current (A/C 1145)",
    notes: "Out-of-pattern wire transfer to overseas bank account.",
    behaviorComparison: "Significant deviation from standard transaction sizes for this account.",
    aiExplanation: "Flagged: Unusual high-value debit velocity to offshore routing codes. SHAP attributes this anomaly to geographic destination and account age mismatches."
  },
  {
    id: "tx-1006",
    amount: 2500.00,
    currency: "INR",
    merchant: "Zomato Dineout",
    category: "leisure",
    date: "2026-06-28T21:30:00Z",
    type: "debit",
    status: "completed",
    riskScore: 5,
    account: "Corporate Credit Card (CCN-2983)",
    notes: "Client dinner meeting - Q3 roadmap presentation.",
    behaviorComparison: "Matches average client entertainment expense limits.",
    aiExplanation: "Verified transaction at standard dining establishment rates."
  },
  {
    id: "tx-1007",
    amount: 12000.00,
    currency: "INR",
    merchant: "Airtel Fiber & Mobile Services",
    category: "utilities",
    date: "2026-06-25T11:00:00Z",
    type: "debit",
    status: "completed",
    riskScore: 4,
    account: "HDFC Current (A/C 1145)",
    notes: "Quarterly corporate broadband connectivity renewal.",
    behaviorComparison: "Matches exact contractual billing amount.",
    aiExplanation: "Standard recurring subscription debit. Zero anomaly markers."
  },
  {
    id: "tx-1008",
    amount: 8500.00,
    currency: "INR",
    merchant: "Uber Rides Corporate",
    category: "leisure",
    date: "2026-06-24T18:45:00Z",
    type: "debit",
    status: "completed",
    riskScore: 6,
    account: "Corporate Credit Card (CCN-2983)",
    notes: "Commute logs for sales team onsite customer audits.",
    behaviorComparison: "Slightly elevated travel volume due to local conference.",
    aiExplanation: "Normal travel expense pattern. Correlates with verified sales schedule."
  },
  {
    id: "tx-1009",
    amount: 32000.00,
    currency: "INR",
    merchant: "Rent - Co-working Space",
    category: "housing",
    date: "2026-07-01T09:00:00Z",
    type: "debit",
    status: "completed",
    riskScore: 3,
    account: "HDFC Current (A/C 1145)",
    notes: "Monthly rental for hot-desking and workspace hub desks.",
    behaviorComparison: "Identical to last 6 billing cycles.",
    aiExplanation: "Contractual fixed overhead payment processed on recurring date."
  },
  {
    id: "tx-1010",
    amount: 4800.00,
    currency: "INR",
    merchant: "Adobe Creative Cloud",
    category: "utilities",
    date: "2026-06-18T05:00:00Z",
    type: "debit",
    status: "completed",
    riskScore: 7,
    account: "Corporate Credit Card (CCN-2983)",
    notes: "Design team software license seat renewal.",
    behaviorComparison: "Fixed subscription fee matching standard rates.",
    aiExplanation: "Standard SaaS software invoice. Risk contribution near zero."
  },
  {
    id: "tx-1011",
    amount: 28000.00,
    currency: "INR",
    merchant: "HDFC Credit Card Payment",
    category: "debt_repayment",
    date: "2026-06-20T10:00:00Z",
    type: "debit",
    status: "completed",
    riskScore: 10,
    account: "Yes Bank Savings (A/C 9812)",
    notes: "Clearing outstanding corporate credit card balances.",
    behaviorComparison: "Standard monthly sweep of card ledgers.",
    aiExplanation: "Internal account ledger transfer. Neutral risk weight."
  },
  {
    id: "tx-1012",
    amount: 350000.00,
    currency: "INR",
    merchant: "Venture Equity Funding Deposit",
    category: "income",
    date: "2026-06-15T15:00:00Z",
    type: "credit",
    status: "completed",
    riskScore: 1,
    account: "Yes Bank Savings (A/C 9812)",
    notes: "Institutional tranche funding installment deposit.",
    behaviorComparison: "Scheduled equity cash-in tranche.",
    aiExplanation: "Validated venture capital deposit. Increases cash runway reserves dynamically."
  },
  {
    id: "tx-1013",
    amount: 42000.00,
    currency: "INR",
    merchant: "Gizmo Electronics Store",
    category: "other",
    date: "2026-06-12T13:40:00Z",
    type: "debit",
    status: "completed",
    riskScore: 55,
    account: "Corporate Credit Card (CCN-2983)",
    notes: "MacBook repair and external storage hardware purchase.",
    behaviorComparison: "Unusual equipment purchase frequency.",
    aiExplanation: "Moderate warning: Elevated discretionary spending on hardware this quarter."
  },
  {
    id: "tx-1014",
    amount: 1500.00,
    currency: "INR",
    merchant: "Swiggy Instamart",
    category: "leisure",
    date: "2026-06-10T09:30:00Z",
    type: "debit",
    status: "completed",
    riskScore: 3,
    account: "Corporate Credit Card (CCN-2983)",
    notes: "Office pantry snacks and refreshment refills.",
    behaviorComparison: "Consistent quarterly pantry expense.",
    aiExplanation: "Low-risk retail grocery purchase."
  },
  {
    id: "tx-1015",
    amount: 25000.00,
    currency: "INR",
    merchant: "Freelancer UI/UX Designer Payment",
    category: "business",
    date: "2026-06-08T16:00:00Z",
    type: "debit",
    status: "completed",
    riskScore: 18,
    account: "HDFC Current (A/C 1145)",
    notes: "Payout for landing page graphic review deliverables.",
    behaviorComparison: "Periodic outsourced project milestone cost.",
    aiExplanation: "Normal contract consulting payout. Invoice matches delivery details."
  },
  {
    id: "tx-1016",
    amount: 75000.00,
    currency: "INR",
    merchant: "Salary Inflow - Consulting Contract",
    category: "income",
    date: "2026-06-05T09:00:00Z",
    type: "credit",
    status: "completed",
    riskScore: 2,
    account: "Yes Bank Savings (A/C 9812)",
    notes: "Retainer inflow from secondary consulting client group.",
    behaviorComparison: "Recurring monthly client retainer.",
    aiExplanation: "Verified income source with stable history."
  },
  {
    id: "tx-1017",
    amount: 95000.00,
    currency: "INR",
    merchant: "Suspect Cash Withdrawal",
    category: "other",
    date: "2026-06-02T11:20:00Z",
    type: "debit",
    status: "completed",
    riskScore: 88,
    account: "HDFC Current (A/C 1145)",
    notes: "Large ATM cash withdrawal in atypical regional location.",
    behaviorComparison: "Significant anomaly in traditional physical cash withdrawal rates.",
    aiExplanation: "High-risk alert: Out-of-pattern ATM cash withdrawal exceeding regional device activity bounds. Recommended for secondary compliance review."
  },
  {
    id: "tx-1018",
    amount: 6500.00,
    currency: "INR",
    merchant: "Slack Technologies Inc",
    category: "utilities",
    date: "2026-06-01T04:00:00Z",
    type: "debit",
    status: "completed",
    riskScore: 5,
    account: "Corporate Credit Card (CCN-2983)",
    notes: "Slack enterprise communication software licensing.",
    behaviorComparison: "Fixed subscription fee matching contract seats.",
    aiExplanation: "Verified software service provider billing. High trust score."
  },
  {
    id: "tx-1019",
    amount: 3500.00,
    currency: "INR",
    merchant: "Zomato Delivery",
    category: "leisure",
    date: "2026-06-15T19:30:00Z",
    type: "debit",
    status: "completed",
    riskScore: 4,
    account: "Corporate Credit Card (CCN-2983)",
    notes: "Late night developer sprint refreshments dinner.",
    behaviorComparison: "Matches general food delivery patterns on development weeks.",
    aiExplanation: "Standard retail food merchant. Zero risk factors."
  },
  {
    id: "tx-1020",
    amount: 15000.00,
    currency: "INR",
    merchant: "HDFC Bank Loan EMI",
    category: "debt_repayment",
    date: "2026-05-08T10:00:00Z",
    type: "debit",
    status: "failed",
    riskScore: 72,
    account: "HDFC Current (A/C 1145)",
    notes: "Declined EMI wire transfer attempt due to gateway sweep lag.",
    behaviorComparison: "Atypical failure on scheduled banking debit cycles.",
    aiExplanation: "Warning: Transaction failed due to host banking system mismatches. Re-execution schedule verified."
  },
  {
    id: "tx-1021",
    amount: 500000.00,
    currency: "INR",
    merchant: "Acme Corp Seed Funding",
    category: "income",
    date: "2026-05-15T10:30:00Z",
    type: "credit",
    status: "completed",
    riskScore: 1,
    account: "Yes Bank Savings (A/C 9812)",
    notes: "Initial institutional Seed round capital deposit.",
    behaviorComparison: "Major capital raise transaction.",
    aiExplanation: "Legitimate institutional investment funding deposit. Positive liquidity impact."
  },
  {
    id: "tx-1022",
    amount: 45000.00,
    currency: "INR",
    merchant: "Google Cloud Platform",
    category: "utilities",
    date: "2026-07-06T02:00:00Z",
    type: "debit",
    status: "completed",
    riskScore: 24,
    account: "Corporate Credit Card (CCN-2983)",
    notes: "Google Cloud compute virtual machines invoice.",
    behaviorComparison: "Consistently maps to monthly cloud allocations.",
    aiExplanation: "Legitimate enterprise technology service provider invoice."
  },
  {
    id: "tx-1023",
    amount: 34000.00,
    currency: "INR",
    merchant: "Rental - Storage Facility",
    category: "housing",
    date: "2026-06-01T08:00:00Z",
    type: "debit",
    status: "completed",
    riskScore: 4,
    account: "HDFC Current (A/C 1145)",
    notes: "Secure storage unit rental invoice.",
    behaviorComparison: "Consistent storage costs.",
    aiExplanation: "Low risk contractual fixed payment."
  },
  {
    id: "tx-1024",
    amount: 7500.00,
    currency: "INR",
    merchant: "GitHub Enterprise",
    category: "utilities",
    date: "2026-07-01T03:00:00Z",
    type: "debit",
    status: "completed",
    riskScore: 5,
    account: "Corporate Credit Card (CCN-2983)",
    notes: "Developer organization seats billing invoice.",
    behaviorComparison: "Fixed subscription based on user configuration.",
    aiExplanation: "Verified developer tool provider payment."
  },
  {
    id: "tx-1025",
    amount: 145000.00,
    currency: "INR",
    merchant: "Unknown Wire Outflow",
    category: "business",
    date: "2026-07-02T16:00:00Z",
    type: "debit",
    status: "completed",
    riskScore: 96,
    account: "HDFC Current (A/C 1145)",
    notes: "High value unverified debit transfer.",
    behaviorComparison: "Significant deviation from standard counterparty listings.",
    aiExplanation: "CRITICAL: Suspicious transfer. Destination account has historical correlation with shell entities. Compliance audit required immediately."
  }
];
